POST http://localhost:5000/cart
Content-Type: application/json

{
    "name": "Pizza-3",
    "price": 15000,
    "qty": 10
}

###
GET http://localhost:5000/cart

###
GET http://localhost:5000/cart/46
###
PATCH  http://localhost:5000/cart/2
Content-Type: application/json

{
    "name": "Pizza-Dua",
    "price": 50000,
    "qty": 2,
    "alt": "Pizza"
}

###
DELETE   http://localhost:5000/cart/71
Content-Type: application/json

###
POST http://localhost:5000/message
Content-Type: application/json

{
    "name": "Nama-1",
    "subject": "Subject-1",
    "email": "Email-1",
    "message": "Message-1"
}

###
GET http://localhost:5000/message

###
DELETE   http://localhost:5000/message/1
Content-Type: application/json

###
GET http://localhost:5000/list

###
POST http://localhost:5000/order
Content-Type: application/json

{
    "name": "Pizza-4",
    "price": "15000",
    "qty": "10"
}

###
GET http://localhost:5000/order